### ISSUE TITLE
MHP.asi issue with loading with the latest Ultimate ASI Loader

### ISSUE THREAD

**Issue by Arijit746255** [Fire-Head/MHP#1]
Hello File-Head, 

I was trying Manhunt with your ASI, and I seem to have hit an issue. 

With the latest Ultimate ASI Loader v4.59, the MHP.asi fails to load with the error "unable to load MHP.asi. Error:126" when launching manhunt.exe. With the previous Ultimate ASI Loader v3.4, no error is displayed but there are no visible differences observed related to PS2 features. This indicates with the Ultimate ASI Loader v3.4 also MHP.asi is not working. 

Could you let me know which version of Ultimate ASI Loader your MHP.asi works ? I do not have the steam version but the retail ISO. OS - Windows 10 ver. 21H1

**Comment by Fire-Head** [comment]
Hello. MHP works with latest v4.59 x86 UAL renamed to "ddraw.dll".

**Comment by Arijit746255** [comment]
Well, I did use the  v4.59 x86 UAL from Github, and it fails with the error "unable to load MHP.asi. Error:126". Not sure.

**Comment by Fire-Head** [comment]
"Error: 126" might be a missing dll.
Please try this version, i removed msvc2010 dependencies.
[MHP.zip](https://github.com/Fire-Head/MHP/files/7071380/MHP.zip)

**Comment by Arijit746255** [comment]
It works now. No errors during loading of MHP.asi. Thanks for resolving this.
